import type { LabelDefinition } from "@/features/labels/label.types";

const labelOssBaseUrl = "https://rapperank.oss-cn-hangzhou.aliyuncs.com/label";

export const labelDefinitions: LabelDefinition[] = [
  {
    id: "cdc",
    slug: "cdc",
    name: "CDC",
    displayName: "成都集团 / 成都说唱会馆",
    alias: "CDC",
    region: "Chengdu",
    description: "成都本土地下到主流都绕不开的一条厂牌脉络，地域辨识度和 cypher 文化都很强。",
    logoUrl: `${labelOssBaseUrl}/CDC.jpg`,
    themeTag: "chengdu core",
    memberIds: ["wang-yitai", "xie-di", "ty", "mengzi-cdc", "sleepy-cat"],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 1,
  },
  {
    id: "gosh",
    slug: "gosh",
    name: "GOSH",
    displayName: "GOSH",
    alias: "重庆 GOSH",
    region: "Chongqing",
    description: "重庆说唱最有代表性的厂牌之一，方言、山城气质和舞台人格都很鲜明。",
    logoUrl: `${labelOssBaseUrl}/GOSH.jpg`,
    themeTag: "mountain city",
    memberIds: ["bridge-gosh", "wang-qiming", "wudu-montana"],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 2,
  },
  {
    id: "mdsk",
    slug: "mdsk",
    name: "MDSK",
    displayName: "MDSK",
    alias: "Modern Sky",
    region: "China",
    description: "摩登天空旗下的说唱品牌线，更偏成熟音乐公司体系与更广泛的舞台曝光。",
    logoUrl: `${labelOssBaseUrl}/MDSK.jpg`,
    themeTag: "industry label",
    memberIds: [],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 3,
  },
  {
    id: "sg",
    slug: "sg",
    name: "SG",
    displayName: "声闻聚将",
    alias: "SevenGurus",
    region: "China",
    description: "以新世代旋律与节目传播并行的一条厂牌线，辨识度更多来自公开舞台与单曲表现。",
    logoUrl: `${labelOssBaseUrl}/SG.jpg`,
    themeTag: "new wave",
    memberIds: ["ice"],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 4,
  },
  {
    id: "shooc",
    slug: "shooc",
    name: "Shooc",
    displayName: "Shooc",
    alias: "Shooc Studio",
    region: "Nanjing",
    description: "Jony J 主理的南京厂牌，强调作品完成度、个人表达和更成熟的创作审美。",
    logoUrl: `${labelOssBaseUrl}/Shooc.jpg`,
    themeTag: "craft label",
    memberIds: ["jony-j"],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 5,
  },
  {
    id: "diss",
    slug: "diss",
    name: "第四音乐",
    displayName: "第四音乐",
    alias: "No.4 Music",
    region: "China",
    description: "更偏公司化运作的一条说唱厂牌线，擅长把地下审美与更广传播场景连接起来。",
    logoUrl: `${labelOssBaseUrl}/diss.jpg`,
    themeTag: "label company",
    memberIds: [],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 6,
  },
  {
    id: "dungeon",
    slug: "dungeon",
    name: "丹镇北京",
    displayName: "丹镇北京",
    alias: "Dungeon Beijing",
    region: "Beijing",
    description: "北京地下说唱的重要据点之一，老派根基、现场文化和城市街头语境都很浓。",
    logoUrl: `${labelOssBaseUrl}/dungeon.jpg`,
    themeTag: "beijing underground",
    memberIds: [],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 7,
  },
  {
    id: "free-out",
    slug: "free-out",
    name: "Free-Out",
    displayName: "Free-Out",
    alias: "南京 Free-Out",
    region: "Nanjing",
    description: "南京地下说唱最具代表性的厂牌之一，网络传播、battle 气质和城市标签都很突出。",
    logoUrl: `${labelOssBaseUrl}/freeout.jpg`,
    themeTag: "nanjing underground",
    memberIds: ["mc-guangguang"],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 8,
  },
  {
    id: "hhh",
    slug: "hhh",
    name: "红花会",
    displayName: "红花会",
    alias: "HHH",
    region: "Xi'an",
    description: "西安说唱历史上影响力极强的一条厂牌与团体线，曾经推动西安声音快速被全国听见。",
    logoUrl: `${labelOssBaseUrl}/hhh.jpg`,
    themeTag: "xian legacy",
    memberIds: [],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 9,
  },
  {
    id: "nous",
    slug: "nous",
    name: "NOUS Underground",
    displayName: "NOUS Underground",
    alias: "NOUS",
    region: "Xi'an",
    description: "西安 battle、cypher 与地下创作体系里很关键的一支力量，成员个体辨识度也强。",
    logoUrl: `${labelOssBaseUrl}/nous.jpg`,
    themeTag: "battle system",
    memberIds: ["pact", "nineone"],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 10,
  },
  {
    id: "sup",
    slug: "sup",
    name: "SUP",
    displayName: "SUP",
    alias: "SUP Music",
    region: "Chengdu",
    description: "更偏专辑审美和创作完整度的一条厂牌线，旋律、文本与作者气质较为统一。",
    logoUrl: `${labelOssBaseUrl}/sup.jpg`,
    themeTag: "album driven",
    memberIds: ["po8"],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 11,
  },
  {
    id: "walking-dead",
    slug: "walking-dead",
    name: "活死人",
    displayName: "活死人",
    alias: "Walking Dead",
    region: "Shanghai",
    description: "以硬核、概念表达和强现场人格著称的厂牌线，作品气质和成员形象都高度统一。",
    logoUrl: `${labelOssBaseUrl}/walkingdead.jpg`,
    themeTag: "hardcore unit",
    memberIds: ["pharaoh", "fox-huosi"],
    memberDisplayNames: [],
    memberPlaceholder: "成员数据待补充",
    status: "active",
    sortOrder: 12,
  },
];
